### ISSUE TITLE
encode_dag_cbor doesn't sort keys while encoding dictionaries

### ISSUE THREAD

**Issue by goeo-** [MarshalX/python-libipld#22] opened 2024-03-03 01:09 UTC
```py
>>> libipld.encode_dag_cbor({"a":1, "b":2})
b'\xa2aa\x01ab\x02'
>>> libipld.encode_dag_cbor({"b":2, "a":1})
b'\xa2ab\x02aa\x01'
```

interestingly, https://github.com/ipld/libipld/blob/master/dag-cbor/src/encode.rs#L276-L296 libipld seems to implement this, but this is seemingly not used? i've had a similar issue with serde_ipld_dagcbor (linked on libipld's readme) and they seem to also implement it in a function that's never called (??)

**Comment by goeo-** [comment] 2024-03-03 01:17
i just noticed that #18 fixed this issue yesterday, however i'll leave the issue open because i think it's weird that you had to sort stuff yourself if libipld is supposed to do it

**Comment by MarshalX** [comment] 2024-03-03 07:45
was fixed in #18. can't reproduce. make sure that you updated python package. this fix was included in https://github.com/MarshalX/python-libipld/releases/tag/v1.2.2

to update use this command: `pip install -U libipld`

<img width="362" alt="image" src="https://github.com/MarshalX/python-libipld/assets/15520314/c3f9af93-d928-4a79-8e86-bea69a040e90">

**Comment by MarshalX** [comment] 2024-03-03 07:56
> i just noticed that #18 fixed this issue yesterday, however i'll leave the issue open because i think it's weird that you had to sort stuff yourself if libipld is supposed to do it

Missed this comment. Well, I think the upstream lib that I use even allow keys in maps that are not strings xddd. So I don't care about their implementation much. Personally I fixed this out of specification thing in my end 

Btw I use libipld instead of serde. Serde based on different crate used for cbor. I mean 2 completely different implementations

**Comment by MarshalX** [comment] 2024-03-03 08:24
> ```py
> 
> >>> libipld.encode_dag_cbor({"a":1, "b":2})
> 
> b'\xa2aa\x01ab\x02'
> 
> >>> libipld.encode_dag_cbor({"b":2, "a":1})
> 
> b'\xa2ab\x02aa\x01'
> 
> ```
> 
> 
> 
> interestingly, https://github.com/ipld/libipld/blob/master/dag-cbor/src/encode.rs#L276-L296 libipld seems to implement this, but this is seemingly not used?

Should be called when you are trying to encode Ipld enum. So you need to build ipld enum first and encode it

**Comment by MarshalX** [comment] 2024-03-10 22:30
closing becuase of inactivity

**Closed by MarshalX** 2024-03-10 22:30 UTC
